
title: Tris Doan
logo: "images/274001952_1616352562042661_2293468603069187119_n.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! Welcome to my project house. Hope you enjoy and have a nice day!
  <br><br>
  <a href="https://www.linkedin.com/in/trisdoan/">View My LinkedIn Profile</a>
  
## About me

I am a highly self-motivated young man with data-driven mindset and tourism knowledge. 
I am excited to start a new journey as I make a big change from the tourism industry to data analytics. 
Rather than looking at that as a negative, I believe my true skills, abilities and passion are best-served aligning with this industry.
There are several skills that I have developed that will be an advantage in completing the tasks required, including SQL, Python and Power BI.
I am now seeking to work in a professional company as a data analyst.

theme: jekyll-theme-minimal
