
title: <p align="center"> Tris Doan </p>
logo: "images/oooo.plus_149.png" # your photo (or logo) here
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/trisdoan/">LinkedIn</a> |
  <a href="https://github.com/Trisdoan">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BSC degree in Computer Science at University of the People.
  <br><br>
  I am currently looking for a DA position
  <br><br>
  </p>  
  
  
theme: jekyll-theme-minimal
